# Generated by Django 6.0.4 on 2026-04-18 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_round_singleschallenge_singlesframe_singlesroll_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name_plural': 'Participations'},
        ),
        migrations.AddField(
            model_name='participation',
            name='enrolled_teams',
            field=models.ManyToManyField(blank=True, related_name='enrolled_participations', to='core.team'),
        ),
        migrations.AddField(
            model_name='participation',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('season', 'game_type', 'name')},
        ),
    ]
