# Generated by Django 6.0.4 on 2026-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_participation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlesroll',
            name='is_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamroll',
            name='is_recorded',
            field=models.BooleanField(default=False),
        ),
    ]
