# Generated by Django 6.0.4 on 2026-04-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
