# Generated by Django 6.0.4 on 2026-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_round_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
