# Generated by Django 6.0.4 on 2026-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_round_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='order',
            field=models.IntegerField(),
        ),
    ]
