# Generated by Django 6.0.4 on 2026-04-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_round_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('date_range', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.season')),
            ],
        ),
    ]
