# Generated by Django 6.0.4 on 2026-04-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seasonschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonschedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
