# Generated by Django 6.0.4 on 2026-04-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seasonschedule_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='hero_image',
            field=models.URLField(blank=True, help_text='URL for the hero background image', null=True),
        ),
    ]
